-- Seed data generated from backend/app/data/skills.json and careers.json

INSERT INTO skills (name, category) VALUES
    ('HTML', 'frontend'),
    ('CSS', 'frontend'),
    ('JavaScript', 'frontend'),
    ('TypeScript', 'frontend'),
    ('React', 'frontend'),
    ('Vue', 'frontend'),
    ('Tailwind CSS', 'frontend'),
    ('Python', 'backend'),
    ('Java', 'backend'),
    ('Node.js', 'backend'),
    ('FastAPI', 'backend'),
    ('Django', 'backend'),
    ('Flask', 'backend'),
    ('Express', 'backend'),
    ('REST APIs', 'backend'),
    ('SQL', 'database'),
    ('PostgreSQL', 'database'),
    ('MySQL', 'database'),
    ('MongoDB', 'database'),
    ('Docker', 'devops'),
    ('Kubernetes', 'devops'),
    ('Git', 'tools'),
    ('Testing', 'quality'),
    ('Authentication', 'backend'),
    ('CI/CD', 'devops'),
    ('Linux', 'tools'),
    ('Machine Learning', 'ai'),
    ('Deep Learning', 'ai'),
    ('Data Analysis', 'data'),
    ('Data Visualization', 'data'),
    ('C++', 'backend'),
    ('C#', 'backend'),
    ('JavaFX', 'frontend'),
    ('PHP', 'backend'),
    ('Redux', 'frontend'),
    ('GraphQL', 'backend'),
    ('Figma', 'design'),
    ('UI/UX Design', 'design');

INSERT INTO career_roles (name, description) VALUES
    ('Frontend Developer', 'Builds user-facing interfaces and interactive web experiences.'),
    ('Full Stack Developer', 'Works across the frontend and backend to ship complete features.'),
    ('Python Developer', 'Builds backend systems, tooling, and automation with Python.'),
    ('Data Analyst', 'Turns raw data into insights and reports for decision-making.'),
    ('AI Engineer', 'Designs and deploys machine learning and AI-driven systems.'),
    ('Backend Developer', 'Designs APIs, databases, and server-side application logic.'),
    ('DevOps Engineer', 'Automates deployment pipelines and manages infrastructure.');

-- Link careers to required skills with importance weights
INSERT INTO career_skills (career_id, skill_id, importance)
SELECT cr.id, s.id, v.importance FROM (VALUES
    ('Frontend Developer', 'HTML', 5),
    ('Frontend Developer', 'CSS', 5),
    ('Frontend Developer', 'JavaScript', 5),
    ('Frontend Developer', 'React', 4),
    ('Frontend Developer', 'TypeScript', 3),
    ('Frontend Developer', 'Tailwind CSS', 2),
    ('Frontend Developer', 'Redux', 2),
    ('Frontend Developer', 'Git', 3),
    ('Frontend Developer', 'Testing', 2),
    ('Frontend Developer', 'UI/UX Design', 2),
    ('Full Stack Developer', 'HTML', 4),
    ('Full Stack Developer', 'CSS', 4),
    ('Full Stack Developer', 'JavaScript', 5),
    ('Full Stack Developer', 'React', 4),
    ('Full Stack Developer', 'Python', 3),
    ('Full Stack Developer', 'Node.js', 3),
    ('Full Stack Developer', 'SQL', 4),
    ('Full Stack Developer', 'PostgreSQL', 3),
    ('Full Stack Developer', 'REST APIs', 5),
    ('Full Stack Developer', 'Authentication', 3),
    ('Full Stack Developer', 'Docker', 3),
    ('Full Stack Developer', 'Git', 3),
    ('Full Stack Developer', 'Testing', 3),
    ('Python Developer', 'Python', 5),
    ('Python Developer', 'FastAPI', 3),
    ('Python Developer', 'Django', 3),
    ('Python Developer', 'Flask', 2),
    ('Python Developer', 'SQL', 4),
    ('Python Developer', 'PostgreSQL', 3),
    ('Python Developer', 'REST APIs', 4),
    ('Python Developer', 'Git', 3),
    ('Python Developer', 'Testing', 3),
    ('Python Developer', 'Docker', 2),
    ('Python Developer', 'Linux', 2),
    ('Data Analyst', 'Python', 4),
    ('Data Analyst', 'SQL', 5),
    ('Data Analyst', 'Data Analysis', 5),
    ('Data Analyst', 'Data Visualization', 4),
    ('Data Analyst', 'PostgreSQL', 2),
    ('Data Analyst', 'Machine Learning', 1),
    ('AI Engineer', 'Python', 5),
    ('AI Engineer', 'Machine Learning', 5),
    ('AI Engineer', 'Deep Learning', 4),
    ('AI Engineer', 'Data Analysis', 3),
    ('AI Engineer', 'SQL', 2),
    ('AI Engineer', 'Docker', 2),
    ('AI Engineer', 'REST APIs', 2),
    ('AI Engineer', 'Git', 2),
    ('Backend Developer', 'Python', 3),
    ('Backend Developer', 'Node.js', 3),
    ('Backend Developer', 'Java', 2),
    ('Backend Developer', 'FastAPI', 2),
    ('Backend Developer', 'Express', 2),
    ('Backend Developer', 'SQL', 4),
    ('Backend Developer', 'PostgreSQL', 3),
    ('Backend Developer', 'MongoDB', 2),
    ('Backend Developer', 'REST APIs', 5),
    ('Backend Developer', 'Authentication', 4),
    ('Backend Developer', 'Docker', 3),
    ('Backend Developer', 'Testing', 3),
    ('Backend Developer', 'Git', 3),
    ('DevOps Engineer', 'Docker', 5),
    ('DevOps Engineer', 'Kubernetes', 5),
    ('DevOps Engineer', 'CI/CD', 5),
    ('DevOps Engineer', 'Linux', 5),
    ('DevOps Engineer', 'Git', 3),
    ('DevOps Engineer', 'Python', 2),
    ('DevOps Engineer', 'SQL', 1)
) AS v(career_name, skill_name, importance)
JOIN career_roles cr ON cr.name = v.career_name
JOIN skills s ON s.name = v.skill_name;
